site_name: py-experimenter-dashboard
repo_url: https://github.com/mwever/py-experimenter-dashboard
site_url: https://mwever.github.io/py-experimenter-dashboard
site_description: This is a dashboard that can be connected to PyExperimenter setups.
site_author: Marcel Wever
edit_uri: edit/main/docs/
repo_name: mwever/py-experimenter-dashboard
copyright: Maintained by <a href="https://mwever.com">mwever</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["py_experimenter_db"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mwever/py-experimenter-dashboard
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/py-experimenter-dashboard

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
